### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by ghost** [kyuupichan/bitcoinX#5]
Would you be open to making bitcoinx compatible with Python 3.5?

Right now, [bitsv](https://github.com/austecon/bitsv) uses bitcoinx and that holds us to a 3.6 requirement. Unfortunately, Debian 9 and others only ship with Python 3.5. If 3.6 doesn't have any deal-breaker features, it'd be nice to support 3.5.

Thank you!

**Comment by kyuupichan** [comment]
No, there are good reasons 3.5 is not admitted.  New syntax and crucial bug fixes.

**Comment by ghost** [comment]
I understand, thanks for getting back to me. Can you explain what the bug fixes are or give me an idea so I'm aware?

**Comment by kyuupichan** [comment]
Sorry I was getting this package confused with aiorpcX where there were many networking bugs in 3.5 (and 3.6 to a lesser extent).

At present the main thing then is the f-strings.  I may be persuadable they could be done away with, though I develop myself with Python3.7 and all my other packages use them so that is a bit painful for me.

I wouldn't want to maintain 3.5 support for long.  Why don't you try running the testsuite on 3.5 and find out what needs changing?

**Comment by ghost** [comment]
Gotcha, thank you! I see at least 45 f-strings. Converting those takes a little while, I imagine it might be faster to make an f() wrapper and then to a search/replace.

I'll first have to clear that up before seeing if anything else is broken but will be busy for at least part of the day today.

**Comment by kyuupichan** [comment]
Closing, nothing seems to be happening
